name: xserver
description: A sample "Hello, World!" Functions Framework project.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  dart_casing: ^3.0.1
  functions_framework: ^0.4.0
  glob: ^2.1.2
  langchain: ^0.3.1+1
  langchain_core: ^0.3.3
  langchain_openai: ^0.6.3
  logging: ^1.2.0
  package_config: ^2.1.0
  path: ^1.9.0
  shelf: ^1.0.0
  shelf_router: ^1.1.4
  shelf_web_socket: ^2.0.0
  source_gen: ^1.5.0
  synchronized: ^3.1.0+1

dev_dependencies:
  build_runner: ^2.4.11
  functions_framework_builder: ^0.4.0
  http: '>=0.13.0 <2.0.0'
  dart_flutter_team_lints: ^1.0.0
  test: ^1.15.7
  test_process: ^2.0.0
