name: xserver
version: 0.1.3
description: A Dart-based web server framework.
repository: https://github.com/shtse8/xserver
homepage: https://github.com/shtse8/xserver

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  collection: ^1.18.0
  dart_casing: ^3.0.1
  http: ^1.2.2
  meta: ^1.12.0
  path: ^1.9.0
  shelf: ^1.0.0
  shelf_router: ^1.1.4
  shelf_web_socket: ^2.0.0
  source_gen: ^1.5.0

dev_dependencies:
  build_runner: ^2.4.11
  dart_flutter_team_lints: ^1.0.0
  test: ^1.15.7
  test_process: ^2.0.0
